# Generated by Django 3.2.8 on 2022-07-27 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=255, verbose_name='وضیحات')),
                ('Amount', models.BigIntegerField(verbose_name='هزینه')),
                ('Date', models.DateTimeField(verbose_name='تاریخ')),
                ('Choose', models.CharField(choices=[('lunch', 'نهار'), ('dinner', 'شام')], default='lunch', max_length=255, verbose_name='انتخاب کنید')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
