# Generated by Django 3.2.8 on 2022-07-27 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bestoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Text',
            field=models.CharField(max_length=255, verbose_name='توضیحات'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('Amount', models.BigIntegerField(verbose_name='درآمد')),
                ('Date', models.DateTimeField(verbose_name='تاریخ')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
