# Generated by Django 3.2.8 on 2022-07-30 13:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Bestoon', '0003_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='expense',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
