# Generated by Django 4.0.6 on 2022-08-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Rate',
            field=models.IntegerField(default='0', verbose_name='امتیاز'),
        ),
    ]
